name: Build
on:
  push:
    branches: [ "main" ]
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ vars.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      run: |
        VERSION=$(cat version.txt)
        NEW_VERSION=$((VERSION + 1))  # Increment the version
        docker build -t peto2505/website:v${NEW_VERSION} .
        docker images
        docker push peto2505/website:v${NEW_VERSION}

    - name: Set up GitHub CLI
      run: |
        # Install GitHub CLI
        sudo apt-get install gh

    - name: Authenticate with GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        gh auth status
    - name: Set up Git
      run: |
        git config --global user.name "Petros2505"
        git config --global user.email "pethov25@gmail.com"

    - name: Update version and commit
      run: |
        VERSION=$(cat version.txt)
        NEW_VERSION=$((VERSION + 1))
        echo $NEW_VERSION > version.txt
        git add version.txt
        git commit -m "Update version to v${NEW_VERSION}"
        
        
        git push
