name: Build 

on:
  push:
    branches: [ "main" ]
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: login to Docker Hub
      run: echo "${{ vars.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      run: |
        docker build -t peto2505/website:${GITHUB_WORKFLOW_SHA} .
        docker images
        docker push peto2505/website:${GITHUB_WORKFLOW_SHA}
