name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from version.txt
        id: read_version
        run: |
          VERSION=$(cat version.txt || echo "v0")
          echo "Current version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Increment version
        id: increment_version
        run: |
          VERSION=$(echo ${{ steps.read_version.outputs.version }} | sed 's/v//')
          VERSION=$((VERSION + 1))
          NEW_VERSION="v$VERSION"
          echo "New version: $NEW_VERSION"
          echo $NEW_VERSION > version.txt
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Build Docker image
        run: |
          docker build -t peto2505/website:${{ steps.increment_version.outputs.new_version }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push peto2505/website:${{ steps.increment_version.outputs.new_version }}

      - name: Commit and push version update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
          git push
